name: Run Tests

on:
  [pull_request]

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install backend modules
      run: npm ci
      working-directory: ./src/server
    - name: Run backend tests
      run: npm run test
      working-directory: ./src/server
  webapp_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install React modules
      run: npm ci
      working-directory: ./src/app
    - name: Run React tests
      run: npm run test
      working-directory: ./src/app