#!/bin/sh

# Bootstrap script supportsd MacOS

# echo "Check if homebrew is installed"
# # Check if homebrew is installed
# which -s brew
# if [[ $? != 0 ]] ; then
#     # Install Homebrew
#     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# fi

# echo "Check if docker is installed"
# # Check if docker is installed
# docker -v
# if [[ $? != 0 ]] ; then
#     brew install --cask docker
# fi

# echo "Starting docker if docker is not running"

# if ! docker info >/dev/null 2>&1; then
#     open -g -a Docker.app || exit
# fi

# until docker info > /dev/null 2>&1; do
#   echo "Waiting for docker to start"
#   sleep 5
# done

# Build docker compose images
docker-compose -f src/docker-compose.yml -p whiletrue build --no-cache
