version: '1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WhileTrue
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  server:
    build:
      context: .
      dockerfile: ServerDockerfile
    volumes:
      - ./server:/server
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    expose:
      - "8080"
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/WhileTrue'
      JWT_SECRET: 'secret'
      CLIENT_URL: 'http://localhost:3000'
    command: "npm start" 
  app:
    build:
      context: .
      dockerfile: AppDockerfile
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: "npm start" 
