name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install backend modules
        run: npm ci
        working-directory: ./src/server
      - name: Run backend tests
        run: npm run test
        working-directory: ./src/server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  webapp_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install React modules
        run: npm ci
        working-directory: ./src/app
      - name: Run React tests
        run: npm run test
        working-directory: ./src/app
        env:
          REACT_APP_MAGIC_PUBLISHABLE_KEY: ${{ secrets.REACT_APP_MAGIC_PUBLISHABLE_KEY }}
